runtime: python27
api_version: 1
threadsafe: yes
service: backend

handlers:
  
# The endpoints handler must be mapped to /_ah/api.
- url: /_ah/api/.*
  script: grader.api

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

env_variables:
  # The following values are to be replaced by information from the output of
  # 'gcloud service-management deploy swagger.json' command.
  ENDPOINTS_SERVICE_NAME: grader-api.endpoints.toefl-grader.cloud.goog
  ENDPOINTS_SERVICE_VERSION: 2017-01-15r0

  # Replace with your Firebase project ID.
  FIREBASE_PROJECT_ID: 'toefl-grader'